name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  HEADLESS_TEST: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update Rustup
      run: rustup self update
    - uses: actions/checkout@v2
    - name: Setup rust-toolchain
      # This looks retarded but it's correct
      # see https://github.com/rust-lang/rustup/issues/2070#issuecomment-545096849
      run: rustup show
    - name: Build
      run: cargo build --verbose
    - name: Run unit tests
      run: cargo test --verbose
    - name: Run basic end to end API tests
      run: ./e2e_tests/api/basic.py
    - name: Install Selenium
      run: sudo apt install python3-selenium
    - name: Run browser test
      run: ./e2e_tests/browser/basic.py
    - name: Clippy
      run: cargo clippy -- -D clippy::all
