name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update Rustup
      run: rustup self update
    - uses: actions/checkout@v2
    - name: Setup rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
